[base]
package = ocean
env_name = slimevolley
policy_name = MinGRU
rnn_name = Recurrent

[vec]
total_agents = 4096

[policy]
num_layers = 2
hidden_size = 64

[env]
; 1 for single-agent (vs bot), 2 for two-agent (self-play)
num_agents=1
gamma = 0.99
[train]
total_timesteps = 500_000_000

[sweep]
downsample = 5

[sweep.train.total_timesteps]
distribution = log_normal
min = 1e8
max = 2e9
mean = 3e8
scale = time

