[base]
package = ocean
env_name = puffer_impulse_wars
policy_name = ImpulseWarsPolicy
rnn_name = ImpulseWarsLSTM
max_suggestion_cost = 10_800

[policy]
hidden_size = 512
cnn_channels = 64

# These must match what's set in env below
continuous = False
num_drones = 2
is_training = True

[vec]
num_envs = 4
#num_workers = 4
#batch_size = 4

[env]
num_envs = 1024
num_drones = 2
num_agents = 1
enable_teams = False
sitting_duck = False
continuous = False
is_training = True

[train]
total_timesteps = 100_000_000
checkpoint_interval = 250

learning_rate = 0.005

compile = False
compile_mode = reduce-overhead
compile_fullgraph = False
device = cuda

[sweep]
downsample = 10
max_cost = 900

[sweep.env.num_envs]
distribution = uniform_pow2
min = 1
max = 1024
mean = 128
scale = auto


